import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

// Concatenate CSS files: fonts.css + core_styles.css -> styles.css
function buildStyles() {
	const fonts = fs.readFileSync("fonts.css", "utf8");
	const core = fs.readFileSync("core_styles.css", "utf8");
	fs.writeFileSync("styles.css", fonts + "\n" + core);
	console.log("Built styles.css");
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	buildStyles();
	await context.rebuild();
	process.exit(0);
} else {
	buildStyles();
	// Watch for CSS changes
	fs.watch("fonts.css", buildStyles);
	fs.watch("core_styles.css", buildStyles);
	await context.watch();
}
